### ISSUE TITLE
Use network shim in paxos protocol

### ISSUE THREAD

**Issue by nano-o** [nano-o/ivy-proofs#2]

**Comment by nano-o** [comment]
At the moment the implementation of `shim.vote_handler.handle` is wrong. The `shim.vote_handler.handle` action is called by the shim when receiving a vote message. Thus it corresponds to `receive_vote_message` (which should be removed).

Action `cast_vote` is also wrong. You should be calling `shim.broadcast` in the `cast_vote` action in order for the node to send a vote message to all other nodes.

**Comment by prasitaGit** [comment]
I implemented the `broadcast` from `cast_vote` but am not quite getting what exactly is the `vote_handler.handle` function supposed to do. Could you give me an high level idea? Like do I have to call an action or initialize some relations. I understand the code flow.  Also  `receive_vote_msg` corresponds to two nodes m and n, whereas in handle we just know the `dst` node.

**Comment by nano-o** [comment]
The idea is that the shim is layer above the network that calls protocol handlers depending on the message type. With `udp_simple` (in the growonly-set example) there is a `recv` action that is implemented by the replica server directly. Here the `recv` action is implemented by the shim. Upon receiving a message, the shim looks at the message type and just calls the corresponding protocol handler.

```
       replica 1                            replica 2

+--+------------------+                +--------------------+
|  |                  |                |    protocol^       |
|  |   protocol       |                |            |       |
+---------------------+                +--------------------+
+---------------------+                +--------------------+
|  |                  |                |     shim   |       |
|  |  shim            |                |            |       |
+---------------------+                +--------------------+
+---------------------+                +--------------------+
|  |                  |                |            |       |
|  |  simple_tcp      |                |    simple_t|p      |
|  |                  |                |            |       |
+---------------------+                +--------------------+
   |                                                ^
   |                                                |
   |                                                |
   |                                                |
   |                                                |
   |                                                |
   |                       message in network       |
   +------>---------------------------------------->+

```

**Comment by nano-o** [comment]
So `shim.vote_handler.handle` is called on replica `r` when `r` receives a vote from another replica. The identity of the sender is not part of the interface, so it must be included in the message.
Right now the implementation of `shim.vote_handler.handle` is wrong. What it should do is update `received_vote_msg` to reflect the fact that the replica received a vote from another replica, and, if a quorum of votes is reached, make a decision.

**Comment by nano-o** [comment]
So `shim.vote_handler.handle` is called on replica `r` when `r` receives a vote from another replica. The identity of the sender is not part of the interface, so it must be included in the message.
Right now the implementation of `shim.vote_handler.handle` is wrong. What it should do is update `received_vote_msg` to reflect the fact that the replica received a vote from another replica, and, if a quorum of votes is reached, make a decision.

**Comment by prasitaGit** [comment]
I have been able to do the first part, i.e., set the receive relation to true. I have not committed yet. To check whether quorum is reached, do we have to maintain some form of counter or the relations will suffice?

**Comment by nano-o** [comment]
The relations will suffice

**Comment by prasitaGit** [comment]
I have been thinking and trying out ways but am failing so far for `quorum` judgement. The primary thing that is confusing me is in order to determine whether a quorum of votes is reached, do we need to store the `quorum` field as well in `msg`? But a node can belong to multiple quorums right?

**Comment by nano-o** [comment]
Can you push your code so that I can make suggestions?

**Comment by prasitaGit** [comment]
Done.

**Comment by nano-o** [comment]
Okay, this is going in the right direction. Have a look at the comment I made in the diff.

**Comment by nano-o** [comment]
Next we're going to use the shim for all the 4 types of messages (`one_a`, `one_b`, `proposal`, `vote`). 
For that, we need a concept of leader (for now, we didn't specify who sends the `one_a` and `proposal` messages).

A simple way to assign a leader to a round is to introduce a function `leader(R:round):node`, which can be left undefined for now. Then, add a node parameter `n` to the `send_1a` and `propose` actions, and add `assume leader(r)=n` etc.  Finally, use the shim to send and receive all three remaining message types, as you did for vote.

**Comment by prasitaGit** [comment]
> Okay, this is going in the right direction. Have a look at the comment I made in the diff.

Which diff? I'm unable to see any changes on pull.

**Comment by prasitaGit** [comment]
> Next we're going to use the shim for all the 4 types of messages (`one_a`, `one_b`, `proposal`, `vote`).
> For that, we need a concept of leader (for now, we didn't specify who sends the `one_a` and `proposal` messages).
> 
> A simple way to assign a leader to a round is to introduce a function `leader(R:round):node`, which can be left undefined for now. Then, add a node parameter `n` to the `send_1a` and `propose` actions, and add `assume leader(r)=n` etc. Finally, use the shim to send and receive all three remaining message types, as you did for vote.

So for that I have to write the implementations of the three handlers as well in `protocol` and pass them from `net.recv` right?

**Comment by nano-o** [comment]
>Which diff? I'm unable to see any changes on pull.

https://github.com/nano-o/ivy-proofs/commit/98804d7ba306b8bee80628d851cc90497ce2730c#r39462985

**Comment by nano-o** [comment]
>So for that I have to write the implementations of the three handlers as well in protocol and pass them from net.recv right?

Yes, there's going to be 4 handlers in total.

**Comment by prasitaGit** [comment]
Also, we should be calling broadcast from `send_1a`, `send_1b` and `propose` right?

**Comment by nano-o** [comment]
Yes

**Comment by prasitaGit** [comment]
I have made some changes. I have added the other functionalities. Haven't removed the assume statement yet. Also i had to add a parameter `v : value` in `send_1a`. I have committed the changes.

**Comment by nano-o** [comment]
`send_1a` does not need the `v` parameter: a `one_a` message is sent by the leader to ask other nodes to join its round. There's no value associated to that.

You will also need to add one more field to the message type for `one_b` messages: nodes to include the round they are joining as well as the max round at which they last voted.

**Comment by prasitaGit** [comment]
> `send_1a` does not need the `v` parameter: a `one_a` message is sent by the leader to ask other nodes to join its round. There's no value associated to that.
> 
> You will also need to add one more field to the message type for `one_b` messages: nodes to include the round they are joining as well as the max round at which they last voted.

So in the broadcast msg, what should be the contents of the value field in send_1a? Should it be left blank?

**Comment by nano-o** [comment]
Yes you can just not set it.

**Comment by prasitaGit** [comment]
Ok. I don't get the second part thought. I mean there is already N,R,MAXR and MAXV in one_b. Don't they specify those?

**Comment by nano-o** [comment]
The goal is now to convey information between nodes using messages only, so that we can eventually generate code that will run in a real distributed system. `one_b` is a global variable that cannot exist in reality. If we want executable code, we cannot use it.

**Comment by prasitaGit** [comment]
i have made the above changes. Could you check and confirm?

**Comment by nano-o** [comment]
Can you also remove `one_b_msg`? Now we have the network so we don't need a variable to represent `one_b` messages. Next, can you implement the `handle` actions?

**Comment by prasitaGit** [comment]
To eliminate `one_b_msg`, I have to remove a bunch of conjectures in protocol which results in two conjectures to fail in `abs.propose`. Do I need to replace those removed conjectures with new conjectures?

**Comment by nano-o** [comment]
Yes, you'll need to replace those conjectures by conjectures that talk about messages in `net.sent`.

**Comment by prasitaGit** [comment]
If I put `net.sent `in any of the conjectures, then on running ivy_check isolate=protocol paxos.ivy, I get errors like this : `paxos.ivy: line 125: error: Call out to shim.broadcast[implement101] may have visible effect on net.sent`
Right now, I am trying to replace `one_b_msg` with `net.sent` in the conjectures.

**Comment by nano-o** [comment]
Yes, that's because you don't have `net` in the `with` clause of your isolate. So Ivy strips all the code that of `net` and thus can't prove anything about `net.sent`, hence the error. More precisely, Ivy sees that you call actions that can modify `net.sent`, but it doesn't know what those modifications are so it emits an error.

**Comment by prasitaGit** [comment]
I have tried replacing `one_b_msg` messages with `net.sent`, but what I observe is the modified conjectures fail which requires me to add more conjectures  to prove the correctness. Is this expected? More conjectures than before.

**Comment by nano-o** [comment]
Yes you'll probably need more conjectures.

**Comment by prasitaGit** [comment]
I have committed some changes. I have modified the conjectures and removed `one_b_msg`. Could you let me know if I am going in the right direction?

**Comment by nano-o** [comment]
Check the comments in your commit on github

**Comment by nano-o** [comment]
You're going in the right direction.

**Comment by prasitaGit** [comment]
> Check the comments in your commit on github

How will I determine from `received_vote_msg` that the message is a `one_b` message? It is updated for every handler right? Do I have to include under field in received_vote_msg that corresponds to the type of msg?

**Comment by nano-o** [comment]
`received_vote_msg` should only record vote messages. You should create another variable `received_one_b_msg` to record which `one_b` messages were received.

Btw I responded to your comment in your last commit. Make sure you get notifications for those things.

**Comment by prasitaGit** [comment]
I have created the variable `received_one_b_msg(N,R,MAXR,V) ` and initialized it to `false`. I am initializing it to true in the handler function of `one_b (shim.oneb_handler.handle)`. I have modified the specifications in proposal. I also tried to modify the conjectures by replacing `net.sent(M,N) `with `received_one_b_msg`, but I see that the four conjectures fail wrt to the action `shim.oneb_handler.handle`. I have committed the changes.

**Comment by prasitaGit** [comment]
Could you look into the above question as well?

**Comment by nano-o** [comment]
>I have created the variable received_one_b_msg(N,R,MAXR,V) and initialized it to false. I am initializing it to true in the handler function of one_b (shim.oneb_handler.handle).

That's correct (just line 189). However the 4 handlers are still incorrect. You'll also need more invariants.

Maybe we should start by developing an implementation that we can run and test, and only then think about the proof. Things would be more concrete that way. What do you think?

**Comment by prasitaGit** [comment]
> > I have created the variable received_one_b_msg(N,R,MAXR,V) and initialized it to false. I am initializing it to true in the handler function of one_b (shim.oneb_handler.handle).
> 
> That's correct (just line 189). However the 4 handlers are still incorrect. You'll also need more invariants.
> 
> Maybe we should start by developing an implementation that we can run and test, and only then think about the proof. Things would be more concrete that way. What do you think?

Fine with me.

**Comment by nano-o** [comment]
Okay, I pushed `rsm_impl.ivy`. It contains an interface for a state-machine service. To start simple, let's implement it for a single server. Can you complete the implementation and test that the generated C++ code works?

**Comment by prasitaGit** [comment]
Sure. i'm on it.

**Comment by prasitaGit** [comment]
Don't you think we need to pass array as a parameter in actions `propose` and `query`?

**Comment by nano-o** [comment]
The idea is that the server maintains an array which is initially empty. If a client calls `propose("a")`, and then the server inserts "a" in the array. If a client then calls `propose("b")`, then the array becomes ["a","b"], and so on. Each time an element is added to the array, the server notifies the client that of the decision to add to the array by calling `notify_decision` (which is trivial for now, but when we'll have multiple replicas it will not be clear to the client what the next decision will be). Finally, if the client calls `query(0)`, the server will look at position 0 in the array a return the value it finds. If the array is ["a","b"], this will be "a". Upon `query(2)` the server returns something with `v.present = false` because 2 is past the array bound.

**Comment by prasitaGit** [comment]
I have committed the changes. Could you check and let me know whether the implementation is correct? I have not called anything yet. It compiles correctly to C++ file.

**Comment by nano-o** [comment]
Okay that's going in the right direction. A couple comments:
* Please remove automatically generated files from the repo (`rsm_impl`, `rsm_impl.cpp`, `rsm_impl.h`).
* It's a good idea to use an abstract data-type for the log, but `set` is not very well suited for that because a set is a different kind of abstraction where we don't care about order. For now just use an array directly in `rsm_impl.ivy`.
* Finally, you should try to run the binary that ivy generates and see what happens.

**Comment by nano-o** [comment]
One thing to keep in mind is that we're trying to implement state-machine replication. If you need more background on that, please read the paper "Implementing fault-tolerant services using the state machine approach: A tutorial". You could also have a look at the Replicant C++ library, notably their interface for state-machines: https://hackingdistributed.com/2013/12/26/introducing-replicant/ (we could borrow their state-machine interface and use it in conjunction with the C++ code we generate).

Anyway, the basic idea is that we want to replicate a log of state-machine operations (you'll see why later), even though the client state-machine only sees the interface we defined. What about we schedule a live chat to discuss the overall approach?

**Comment by nano-o** [comment]
I could do tomorrow Friday 9am if that works for you

**Comment by prasitaGit** [comment]
> I could do tomorrow Friday 9am if that works for you

Fine. Through skype?

**Comment by nano-o** [comment]
I sent you an invite

**Comment by prasitaGit** [comment]
> Okay that's going in the right direction. A couple comments:
> 
> * Please remove automatically generated files from the repo (`rsm_impl`, `rsm_impl.cpp`, `rsm_impl.h`).
> * It's a good idea to use an abstract data-type for the log, but `set` is not very well suited for that because a set is a different kind of abstraction where we don't care about order. For now just use an array directly in `rsm_impl.ivy`.
> * Finally, you should try to run the binary that ivy generates and see what happens.

Ok. Should I use the destructor repr or not (for the array) ?

**Comment by nano-o** [comment]
No need for that. `repr` is only used when defining new abstract data-types.

**Comment by prasitaGit** [comment]
i have removed the files and done the changes (i.e., removed the set implementation). Could you let me know if this is the correct approach?

**Comment by nano-o** [comment]
That's better. Have you tried running it?

**Comment by prasitaGit** [comment]
Not yet. I can generate cpp files. What should be the parameters to provide for running? I mean alongside ./rsm_impl?

**Comment by nano-o** [comment]
Nothing else. This should give you a prompt where you can call actions. For example, try `service_interface.propose("a")`

**Comment by nano-o** [comment]
Also don't forget to run `ivy_check`. No need to prove the interface properties for now, but you should at least make sure that the requirements of the array module are satisfied. For now the program crashes because of illegal calls to the array module.

**Comment by prasitaGit** [comment]
> Also don't forget to run `ivy_check`. No need to prove the interface properties for now, but you should at least make sure that the requirements of the array module are satisfied. For now the program crashes because of illegal calls to the array module.

If I run `ivy_check isolate=impl rsm_impl.ivy` it gives me OK.

**Comment by prasitaGit** [comment]
> Nothing else. This should give you a prompt where you can call actions. For example, try `service_interface.propose("a")`

I am getting this error : 
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

**Comment by nano-o** [comment]
When you do `ivy_check isolate=impl...` Ivy strips all the specifications, which include the requirements of the array module. So you need to run `ivy_check` without specifying an isolate.

**Comment by nano-o** [comment]
As always you can use `ivy_show isolate=impl ...` to see exactly what code Ivy will check.

**Comment by prasitaGit** [comment]
I tried to fix the errors (the array get and set) with respect to query and propose. I can see I do not get the get error anymore (`line 105 collections.ivy`) . However, the set error (in action `propose`) is not resolved. The changes i made lead to further violations in lines 28 and 29 of `rsm_impl.ivy`. I have committed the changes.

**Comment by nano-o** [comment]
Let's fix the errors from `collections.ivy` first. I still see there still is a failure at line 98. This is because you use `+`. If you use `ivy_show isolate=this rsm_impl.ivy` you will see that there are no assumptions about `+`, and because `inst_t` is just an uninterpreted type at the specification level, Ivy does _not_ interpret `+` to be integer addition. So it's just an arbitrary function. Instead you should use the increment action that is specified in the `unbounded_sequence` module.

**Comment by prasitaGit** [comment]
> Let's fix the errors from `collections.ivy` first. I still see there still is a failure at line 98. This is because you use `+`. If you use `ivy_show isolate=this rsm_impl.ivy` you will see that there are no assumptions about `+`, and because `inst_t` is just an uninterpreted type at the specification level, Ivy does _not_ interpret `+` to be integer addition. So it's just an arbitrary function. Instead you should use the increment action that is specified in the `unbounded_sequence` module.

Thanks. This is resolved now. The `collections.ivy` related issues are resolved I think. But the other errors still remain (`invariant` and `ensure`). Running `rsm_impl `with an action also still fails. Do I need to add further conjectures to resolve this?

**Comment by nano-o** [comment]
The crash looks like an Ivy bug, which I reported here: https://github.com/microsoft/ivy/issues/74

Your code is resizing the array using a default value `0`. This should not make the code crash, especially since Ivy verifies it successfully, buy it does because Ivy does not interpret `0` correctly. Here `0` is an arbitrary constant of type `value_t` (like `+` was an arbitrary function of type `inst_t -> inst_t -> inst_t`. I think Ivy should pick an arbitrary string to interpret `0`, but let's see what Ken says.
 
Anyway, a simpler way to do things would be to use `array.append`. Also, the name `my_set` is confusing (it's not a set). Please rename to something like `my_log`.

**Comment by nano-o** [comment]
After you fix this try to eliminate all `ivy_check` errors. You will need to add invariants and probably fix the interface specification too.

**Comment by prasitaGit** [comment]
I am trying to eliminate all ivy_check errors. I have 4 errors now. On `diagnose=true`, ivy gives me the counterexample view of line 26 (`invariant log(I,V1) & log(I,V2) -> V1 = V2`). But I can't see the pointer to `V1` or `V2` and also `log(I,V)` been assigned to true before and after the execution. I have stepped into both `propose` as well as `notify_decision`, but I still can't see anything. I tried the option gather, still nothing. Could you check and tell? I have committed the code.

**Comment by nano-o** [comment]
I'm not sure what's going here. Try with the new isolate definitions that I added.

**Comment by prasitaGit** [comment]
> I'm not sure what's going here. Try with the new isolate definitions that I added.

The command for running should be `ivy_check rsm_impl.ivy` right?

**Comment by prasitaGit** [comment]
Also could you explain the purpose of post conditions (As to what purpose do they serve from the algo perspective). I am having difficulty to eliminate the errors without completely understanding the purpose of ensure statements.

**Comment by nano-o** [comment]
Running `ivy_check` on the whole file is always a good idea. But now you can also check the interface separately from the implementation.

The pre and post-conditions in the interface specification say that `notify_decision` can only be called if the log is still empty at the given position or if it contains the same value at the given position. Similarly, query returns a value with present to true only if the log actually contains the value at the given index.

**Comment by prasitaGit** [comment]
Since `notify_decision` is an internal action, `ensure proposed(v)` is failing when called from the environment. i can't figure out a way to resolve this.

**Comment by nano-o** [comment]
`notify_decision` is only called by `service_implementation`, not the environment. So you need an invariant relating `service_implementation.my_log` and `service_interface.log`.

**Comment by nano-o** [comment]
For `proposed` you also need to track what was proposed in the spec. For now, `proposed` is never set to true in the spec.

**Comment by prasitaGit** [comment]
I have made some changes. I have set `proposed(v)` to true in `after propose`. 

> `notify_decision` is only called by `service_implementation`, not the environment. So you need an invariant relating `service_implementation.my_log` and `service_interface.log`.

For this I tried to link `log(I,V)` with `propose(V)` in the invariant. 
intially I had 2 errors left. But this has added another error.

Also, I am not entirely sure why this counterexample is shown (for propose and query). It shows the same value belongs to both 0 and 1. The value to be added is marked as 1 (and it is not added ultimately), which results in the violation of `ensure log(i,V) -> V = v;`.

![102567268_1125702317798171_391420581280148754_n](https://user-images.githubusercontent.com/54381461/84315935-f296c080-ab2f-11ea-8159-823f50f51a25.jpg)
This is state 0.

![103369748_2538761729771318_4513581308938637688_n](https://user-images.githubusercontent.com/54381461/84315974-fde9ec00-ab2f-11ea-9df3-cfb6d57d9a28.jpg)
This is state 1

i can see the only change is the `inst` pointed by `my_log`.

**Comment by nano-o** [comment]
I don't see what the arrows mean on your picture. Can you use `trace=true` instead of `diagnose=true`? The text representation of counter-examples should be easier to post here.

**Comment by nano-o** [comment]
Anyway, you will need to set `proposed(v)` to true before the `propose` action, otherwise the `require proposed(v)` in `notify_decision` will not be true yet.

Also, you will need an invariant relating `my_log` and `log`. Otherwise, when `service_implementation` calls `notify_decision`, `require log(i,V) -> V = v` will not pass. 

Finally it's wrong to call `notify_decision` in `query`.

**Comment by prasitaGit** [comment]
> I don't see what the arrows mean on your picture. Can you use `trace=true` instead of `diagnose=true`? The text representation of counter-examples should be easier to post here.

```
    The following program assertions are treated as guarantees:
        in action service_interface.notify_decision when called from service_interface.propose,service_interface.query:
            rsm_impl.ivy: line 34: guarantee ... FAIL
searching for a small model... done
[
    value_opt_t.present(0) = false
    service_implementation.arr.end(0) = 0
    service_implementation.arr.end(1) = 1
    0:inst_t = 0
    __V = 0
    0:inst_t < 1 = true
    1:inst_t < 1 = false
    1:inst_t < 0 = false
    0:inst_t < 0 = false
    inst_t.succ(1,1) = false
    inst_t.succ(1,0) = false
    inst_t.succ(0,1) = false
    inst_t.succ(0,0) = false
    service_implementation.arr.value(0,1) = 1
    service_implementation.arr.value(0,0) = 1
    service_implementation.arr.value(1,1) = 1
    service_implementation.arr.value(1,0) = 1
    value_opt_t.value(0) = 0
    service_interface.proposed(0) = false
    service_interface.proposed(1) = false
    service_interface.log(1,0) = true
    service_interface.log(0,0) = true
    service_interface.log(1,1) = false
    service_interface.log(0,1) = false
    service_implementation.my_log = 0
]
fail call service_interface.propose
{
    [
        fml:v = 1
    ]
    rsm_impl.ivy: line 26: assume (service_interface.log(I,V1) & service_interface.log(I,V2)) -> V1 = V2

    rsm_impl.ivy: line 38: service_interface.proposed(fml:v) := true

    [
        service_interface.proposed(1) = true
    ]
    rsm_impl.ivy: line 56: loc:i := service_implementation.arr.end(service_implementation.my_log)

    [
        loc:i = 0
    ]
    rsm_impl.ivy: line 58: call service_implementation.my_log := service_implementation.arr.append(service_implementation.my_log, fml:v)
    {
        [
            old_fml:a_a = 0
            fml:v_a = 1
            fml:a_a = 0
        ]
        fml:a := *

        [
            fml:a_a = 1
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 119: assume (service_implementation.arr.end(fml:a) > service_implementation.arr.end(old_fml:a) & ~(service_implementation.arr.end(old_fml:a) < X & X < service_implementation.arr.end(fml:a)))

        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 121: assume (0:inst_t <= X & X < service_implementation.arr.end(old_fml:a)) -> service_implementation.arr.value(fml:a,X) = service_implementation.arr.value(old_fml:a,X)

        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 122: assume service_implementation.arr.value(fml:a,service_implementation.arr.end(old_fml:a)) = fml:v

    }

    [
        service_implementation.my_log = 1
    ]
    rsm_impl.ivy: line 60: call service_interface.notify_decision(loc:i, fml:v)
    {
        [
            fml:i = 0
        ]
        rsm_impl.ivy: line 33: assume service_interface.proposed(fml:v)

        rsm_impl.ivy: line 34: assert service_interface.log(fml:i,V) -> V = fml:v

    }

}
```
Here is the textual representation obtained with `trace=true`

**Comment by nano-o** [comment]
I that trace I can see that `service_interface.log(0,0) = true` but `notify_decision(0,1)` is called, so the property at line 34 is violated. The problem is that `my_log` has length `0` at the beginning of `propose`, but the abstract log (i.e. `service_interface.log`) is not empty. You need to find an invariant to rule that out. As usual, to see what code Ivy is actually considering, use `ivy_show isolate=service_implementation.iso rsm_impl.ivy`.

**Comment by prasitaGit** [comment]
I have committed some changes. I don't see the violation of `ensure log(i,V) -> V = v` anymore. The present violation that `ivy_check` gives me is the violation of `ensure v.present -> log(i,v.value)`. In the counterexample displayed below, i think it shows that at index 0 there is a value and present is true, but `log(i,v)` is false. For this I tried to formulate an invariant saying that if there is a value V at index I, then log(I,V) should be true. But I am unable to use `arr.get` in an invariant. Please see the trace below : 

```
searching for a small model... done
[
    value_opt_t.present(0) = true
    inst_t.succ(1,1) = false
    inst_t.succ(1,0) = false
    inst_t.succ(0,1) = false
    inst_t.succ(0,0) = false
    value_opt_t.value(0) = 0
    service_implementation.arr.value(0,1) = 0
    service_implementation.arr.value(0,0) = 0
    0:inst_t < 1 = true
    1:inst_t < 1 = false
    1:inst_t < 0 = false
    0:inst_t < 0 = false
    service_implementation.arr.end(0) = 1
    0:inst_t = 0
    service_interface.log(1,0) = false
    service_interface.log(0,0) = false
    service_implementation.my_log = 0
]
fail call service_interface.query
{
    [
        fml:v = 0
        fml:i = 0
    ]
    rsm_impl.ivy: line 28: assume ~service_interface.log(service_implementation.arr.end(service_implementation.my_log),V)

    rsm_impl.ivy: line 27: assume (service_interface.log(I,V1) & service_interface.log(I,V2)) -> V1 = V2

    [
        fml:y = 0
    ]
    rsm_impl.ivy: line 70: call value_opt_t.value(fml:v) := service_implementation.arr.get(service_implementation.my_log, fml:i)
    {
        [
            fml:a = 0
            fml:x = 0
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 105: assert (0:inst_t <= fml:x & fml:x < service_implementation.arr.end(fml:a))

        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 108: assume service_implementation.arr.value(fml:a,fml:x) = fml:y

    }

    rsm_impl.ivy: line 42: assert value_opt_t.present(fml:v) -> service_interface.log(fml:i,value_opt_t.value(fml:v))

}
```

**Comment by nano-o** [comment]
Have a look at the array module in `collections.ivy`. There are other relations and functions you can use to express the invariant.

**Comment by prasitaGit** [comment]
I have committed a change. I have one failed check now. The new invariant : `invariant (service_implementation.my_log.value(I) = V) -> log(I,V) `fails on initialization. Here is the trace : 

```
searching for a small model... done
[
    @I = 0
    service_implementation.arr.value(0,0) = 0
    @V = 0
    service_implementation.my_log = 0
]
init

{
    rsm_impl.ivy: line 30: service_interface.proposed(V) := false

    [
        service_interface.proposed(0) = false
    ]
    rsm_impl.ivy: line 31: service_interface.log(I,V) := false

    [
        service_interface.log(0,0) = false
    ]
}
```
I can see that the array is non empty on init in the counterexample.

**Comment by nano-o** [comment]
You need to take into account that an array has a length.

**Comment by prasitaGit** [comment]
> You need to take into account that an array has a length.

I am not sure what I should imply? Like should I put an and condition to the LHS of the new invariant that `my_log.end > 0` ?

**Comment by nano-o** [comment]
`log(I,V)` should be false if `I` is not within the array's bounds.

**Comment by prasitaGit** [comment]
> `log(I,V)` should be false if `I` is not within the array's bounds.

Don't you think this holds in the trace above. log(I,V) is false. I tried to solve it by adding another invariant : `invariant (I >= service_implementation.my_log.end) -> ~log(I,V)`. But the same counterexample is produced.

**Comment by nano-o** [comment]
Yes you're right that  this counter-example does not have to do with this property. One problem may be that, as you can see with `ivy_show`, there's no specification for `arr.empty()` in the isolate.

**Comment by prasitaGit** [comment]
> Yes you're right that this counter-example does not have to do with this property. One problem may be that, as you can see with `ivy_show`, there's no specification for `arr.empty()` in the isolate.

What is the isolate you specified with ivy_show ?

**Comment by nano-o** [comment]
It's the isolate in which verification fails on initialization. Look at the output of `ivy_check` and see what isolate it's checking.

**Comment by prasitaGit** [comment]
> It's the isolate in which verification fails on initialization. Look at the output of `ivy_check` and see what isolate it's checking.

I modified the iso of service_interface to this :  `isolate iso = this with service_implementation, inst_t`. I can see the arr.empty() in after init now for both `service_interface.iso `and `service_implementation.iso`, but the invariant still fails on initialization.

**Comment by nano-o** [comment]
It shouldn't appear in `service_interface.iso`. The problem is that the specification of `arr.empty()` does not appear in `service_implementation.iso`, so the call to `arr.empty()` in `init` is meaningless when verifying `service_implementation.iso`.

**Comment by prasitaGit** [comment]
But if I do a check with `ivy_show isolate=service_implementation.iso rsm_impl.ivy`, I do get this displayed : 

```
after init {
    {
        call service_implementation.my_log := service_implementation.arr.empty
    }
}

```

**Comment by nano-o** [comment]
Yes, but you should also see a specification for `arr.empty`. If not, then `my_log` is just arbitrary after this call.

**Comment by prasitaGit** [comment]
Should I separate service_implementation into specification and implementation blocks then?

**Comment by nano-o** [comment]
No, you just need to add to the isolate definition.

**Comment by nano-o** [comment]
The things after `with` tell Ivy what other specifications to consider when verifying the isolate. That's where you add all the objects whose specification you need for the proof.

**Comment by prasitaGit** [comment]
On changing the isolate of `service_implementation` to `isolate iso = this with service_interface, inst_t, arr` I get the same error.

**Comment by nano-o** [comment]
Now the problem is that the invariant at line 28 mentions `my_log`, which is a variable of `service_implementation` that the interface should not have to know about. The place for this invariant is in `service_implementation` (also because the invariant will be used to prove that the implementation is correct with respect to the interface specification, and not to prove properties of the interface per se)

**Comment by prasitaGit** [comment]
I have committed the changes. Could you let me know whether this is what you want?

**Comment by nano-o** [comment]
Yes this looks better but there are still some failures. You also have another invariant in the interface that mentions `my_log`. The idea is that from the outside (i.e. from the point of view of applications using the service), we should only see the interface, which hides the implementation. `my_log` is part of the implementation, so it shouldn't appear anywhere in the interface.

**Comment by nano-o** [comment]
Also the `ensure` at line 33 should be a `require`: in the specification of `notify_decision`, we want to say that the `service_implementation` cannot call `notify_decision` with a value that has not been proposed. So it's a requirement on the caller. In contrast, `ensure proposed(v)` would mean that it's the responsibility of the implementer of `notify_decision` (i.e. the client application) to make sure that `proposed(v)` is true, which it obviously can't enforce since it's not the one calling `notify_decision`.

**Comment by nano-o** [comment]
It might be useful to read or review <https://microsoft.github.io/ivy/examples/specification.html> if you have some doubts about interfaces and assume-guarantee reasoning.

**Comment by prasitaGit** [comment]
> Yes this looks better but there are still some failures. You also have another invariant in the interface that mentions `my_log`. The idea is that from the outside (i.e. from the point of view of applications using the service), we should only see the interface, which hides the implementation. `my_log` is part of the implementation, so it shouldn't appear anywhere in the interface.

I see. Since the implementation isolate includes the interface and not vice-versa, we should move the invariants with my_log below. 



> Also the `ensure` at line 33 should be a `require`: in the specification of `notify_decision`, we want to say that the `service_implementation` cannot call `notify_decision` with a value that has not been proposed. So it's a requirement on the caller. In contrast, `ensure proposed(v)` would mean that it's the responsibility of the implementer of `notify_decision` (i.e. the client application) to make sure that `proposed(v)` is true, which it obviously can't enforce since it's not the one calling `notify_decision`.

Actually I don't have a clear picture of the `require` and `ensure` inside a `before` fragment.

**Comment by prasitaGit** [comment]
> It might be useful to read or review https://microsoft.github.io/ivy/examples/specification.html if you have some doubts about interfaces and assume-guarantee reasoning.

Sure. I will look into it. I have committed the changes. Still I can see that line 72 (`invariant ~service_interface.log(my_log.end ,V)`) under propose action. What confuses me is that there are two array pointers  (0 and 1) for two inst values. Here is the trace : 

```
searching for a small model... done
[
    value_opt_t.present(0) = false
    service_implementation.arr.end(0) = 0
    service_implementation.arr.end(1) = 1
    0:inst_t = 0
    @V = 0
    value_opt_t.value(0) = 0
    0:inst_t < 1 = true
    1:inst_t < 1 = false
    1:inst_t < 0 = false
    0:inst_t < 0 = false
    inst_t.succ(1,1) = false
    inst_t.succ(1,0) = false
    inst_t.succ(0,1) = false
    inst_t.succ(0,0) = false
    service_implementation.arr.value(0,1) = 0
    service_implementation.arr.value(0,0) = 0
    service_implementation.arr.value(1,1) = 0
    service_implementation.arr.value(1,0) = 0
    service_interface.proposed(0) = false
    service_interface.log(1,0) = true
    service_interface.log(0,0) = false
    service_implementation.my_log = 0
]
call service_interface.propose

{
    [
        fml:v = 0
    ]
    rsm_impl.ivy: line 26: assume (service_interface.log(I,V1) & service_interface.log(I,V2)) -> V1 = V2

    rsm_impl.ivy: line 37: service_interface.proposed(fml:v) := true

    [
        service_interface.proposed(0) = true
    ]
    rsm_impl.ivy: line 55: loc:i := service_implementation.arr.end(service_implementation.my_log)

    [
        loc:i = 0
    ]
    rsm_impl.ivy: line 56: call service_implementation.my_log := service_implementation.arr.append(service_implementation.my_log, fml:v)
    {
        [
            old_fml:a_a = 0
            fml:v_a = 0
            fml:a_a = 0
        ]
        fml:a := *

        [
            fml:a_a = 1
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 119: assume (service_implementation.arr.end(fml:a) > service_implementation.arr.end(old_fml:a) & ~(service_implementation.arr.end(old_fml:a) < X & X < service_implementation.arr.end(fml:a)))

        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 121: assume (0:inst_t <= X & X < service_implementation.arr.end(old_fml:a)) -> service_implementation.arr.value(fml:a,X) = service_implementation.arr.value(old_fml:a,X)

        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 122: assume service_implementation.arr.value(fml:a,service_implementation.arr.end(old_fml:a)) = fml:v

    }

    [
        service_implementation.my_log = 1
    ]
    rsm_impl.ivy: line 57: call service_interface.notify_decision(loc:i, fml:v)
    {
        [
            fml:i = 0
        ]
        rsm_impl.ivy: line 32: assert service_interface.proposed(fml:v)

        rsm_impl.ivy: line 33: assert service_interface.log(fml:i,V) -> V = fml:v

        rsm_impl.ivy: line 34: service_interface.log(fml:i,fml:v) := true

        [
            service_interface.log(0,0) = true
        ]
        rsm_impl.ivy: line 26: assume (service_interface.log(I,V1) & service_interface.log(I,V2)) -> V1 = V2

    }

}
```

**Comment by nano-o** [comment]
With `require p` in an action `a`, the caller of `a` (i.e. the object that calls action `a`) is responsible for establishing that `p` is true at the beginning of `a` (if this appears in a `before` block). With `ensure p`, the callee (i.e. the object that implements `a`) is responsible for establishing that `a` is true at the end of the action (if this appears in an `after` block. I can't think of a use case for having `ensure` in a `before` block, or `require` in an `after` block, but maybe there is.

You can easily see for yourself what `ensure` and `require` do by using `ivy_show`: Ivy translates `require` and `ensure` to `assume` and `assert` depending on whether you are verifying the caller or the callee.

Try on this example:
```
#lang ivy1.7
relation p
relation q
object interface = {
    action a
    before a {
        require p
    }
    after a {
        ensure q
    }
}
object callee = {
    implement interface.a {
    }
    isolate iso = this with interface
}
object caller = {
    export action b = {
        call interface.a
    }
    isolate iso = this with interface
}
```

**Comment by nano-o** [comment]
As for the invariant, it is still not strong enough and there is a counter-example.
You see two different arrays because arrays are immutable values, and thus updating an array means replacing it with a different array that has the same contents as the previous one except for the updated positions. The arrows in the graphical interface are not pointers, they just represent relations.

**Comment by prasitaGit** [comment]
I tried adding a new invariant and committed the change. The counterexample trace below still shows that `arr.empty` is violated (and it occurs on init) : 

```
searching for a small model... done
[
    @I = 0
    inst_t.succ(0,0) = false
    value_opt_t.present(0) = false
    value_opt_t.value(0) = 0
    0:inst_t < 0 = false
    service_implementation.arr.end(0) = 0
    service_implementation.arr.value(0,0) = 0
    0:inst_t = 0
    @V = 0
]
init

{
    rsm_impl.ivy: line 28: service_interface.proposed(V) := false

    [
        service_interface.proposed(0) = false
    ]
    rsm_impl.ivy: line 29: service_interface.log(I,V) := false

    [
        fml:a = 0
        service_interface.log(0,0) = false
    ]
    rsm_impl.ivy: line 52: call service_implementation.my_log := service_implementation.arr.empty
    {
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 89: assume service_implementation.arr.end(fml:a) = 0

    }

    [
        service_implementation.my_log = 0
    ]
}
```

**Comment by prasitaGit** [comment]
I have committed the changes. They pass now. `ivy_check rsm_impl.ivy` returns OK.

**Comment by nano-o** [comment]
Okay that looks good. Now let's try to make the interface available on a set of nodes, not just one, and implement the necessary synchronization using a fixed leader. I'll create a new issue for that.
