### ISSUE TITLE
Implement distributed RSM interface using a fixed leader

### ISSUE THREAD

**Issue by nano-o** [nano-o/ivy-proofs#3]
As a first step, can you comment out the implementation object a make the specification a parameterized object where the parameter is a node? The goal is to specify that the service interface is available on all nodes. Make sure you read or review <https://microsoft.github.io/ivy/examples/leader.html> if you need more info on parameterized objects.

**Comment by prasitaGit** [comment]
I have committed the changes. Could you check and let me know?

**Comment by nano-o** [comment]
Okay, good. Now un-comment the implementation and make it a parameterized object too. Make the minimum number of changes so that `ivy_check` does not report interference errors (but it's okay if invariants fail) and `ivyc` can produce some code and compile it.

**Comment by prasitaGit** [comment]
I have committed some changes. After uncommenting and making changes in the implementation, this interference error is there : 
`Isolate service_implementation.iso: rsm_impl.ivy: line 38: error: assignment may be interfering`. I am unable to resolve it.

**Comment by nano-o** [comment]
`service_implementation.iso` includes `service_interface`, but it should be `service_interface(n)`.

**Comment by nano-o** [comment]
Then you'll have to move the array instance outside the parameterized object. Creating a separate definition of the array datatype for each node doesn't work here.

**Comment by prasitaGit** [comment]
I have done the above changes and committed the code. `ivy_check` returns OK now. But on `ivyc isolate=impl rsm_impl.ivy,` I get the error : `error: No implementation for action arr.get`

**Comment by nano-o** [comment]
You probably forgot to add the arr object to the code isolate.

**Comment by prasitaGit** [comment]
Thanks. I have pushed the code. `ivy_check` returns OK and `ivyc` compiles successfully.

**Comment by nano-o** [comment]
Okay, now let's introduce a parameter `leader` of type node  (with `parameter leader:node`). Formally it is like `individual leader:node` except that the value for the parameter can be given on the command line at runtime.

Now, upon `propose`, a node is going to send the proposed value to the leader in a message of type `propose_msg`. Upon receiving a propose message, the leader will append the value included in the message to its local log, and then broadcast a message of type `decision_msg` containing the value just appended and the index at which it now sits in the leader's log. All nodes will then insert the value at the indicated position in their own local logs.

Can you implement this using `simple_tcp` from the Ivy library? Feel free to copy stuff from `network_shim.ivy` if you would like.

Also, make sure you review <https://microsoft.github.io/ivy/examples/networking.html>

**Comment by prasitaGit** [comment]
> Okay, now let's introduce a parameter `leader` of type node (with `parameter leader:node`). Formally it is like `individual leader:node` except that the value for the parameter can be given on the command line at runtime.
> 
> Now, upon `propose`, a node is going to send the proposed value to the leader in a message of type `propose_msg`. Upon receiving a propose message, the leader will append the value included in the message to its local log, and then broadcast a message of type `decision_msg` containing the value just appended and the index at which it now sits in the leader's log. All nodes will then insert the value at the indicated position in their own local logs.
> 
> Can you implement this using `simple_tcp` from the Ivy library? Feel free to copy stuff from `network_shim.ivy` if you would like.
> 
> Also, make sure you review https://microsoft.github.io/ivy/examples/networking.html

I'm in the process of implementing this. One question though : So in propose, the node will no longer append the value and call `notify_decision`?

**Comment by nano-o** [comment]
>I'm in the process of implementing this. One question though : So in propose, the node will no longer append the value and call notify_decision?

That's right. Now the node will first contact the leader, wait for a response from the leader, and only then add the value to its own log (at the position given by the leader) and call `notify_decision`.

**Comment by prasitaGit** [comment]
I have committed some changes. I am getting the following error now : 
```
/home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 227: error: assertion is not checked
/home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 221: error: ...in action node.iter.next
rsm_impl.ivy: line 91: error: ...when called from service_implementation.net_recv[implement255]
error: Some assertions are not checked

```
Is this because of the fact that there is no invariant present?

**Comment by nano-o** [comment]
I think this is because you forgot to add some objects to the with clause of some isolate. You call an action that contains a require statement but you don't include the objet containing the definition of the action. Thus the requirement is not checked.

**Comment by prasitaGit** [comment]
I have committed the changes. Those errors are gone. But now i have this interference error : 
`Isolate service_implementation.iso: /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/tcp.ivy: line 184: error: assignment may be interfering`
Line 184 corresponds to : `sent(v,dst) := true`

**Comment by prasitaGit** [comment]
> I have committed the changes. Those errors are gone. But now i have this interference error :
> `Isolate service_implementation.iso: /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/tcp.ivy: line 184: error: assignment may be interfering`
> Line 184 corresponds to : `sent(v,dst) := true`

Resolved this by adding `net(n)` in isolate `service_implementation.iso`. Then I get this error : 
`Isolate service_implementation.iso: error: cannot strip parameter v from net.sent` on `ivy_check`

**Comment by nano-o** [comment]
With `net(n)`, you are asking Ivy to project `net` on node `n`. For this to be applicable, all relations and actions of `net` must have a node as first component (which indicates where the corresponding state lives, or where the action is called). However, if you look at the specification of `net`, you will see that e.g. `sent` does not have a node as first component. So `net(n)` does not make sense.

So you'll have to define the isolate outside of the parameterized object `service_implementation`. This way you won't have to project on `n`.
```
isolate implementation_iso = service_implementation with net, ...`
```

**Comment by prasitaGit** [comment]
I have committed the changes. I have 10 failed checks now. Should I proceed to remove them now? (Or do I have to fix anything else?)

**Comment by nano-o** [comment]
It looks good, but can you first run it with 3 nodes and check that everything works as intended?

**Comment by nano-o** [comment]
It might be worth fixing the guarantees that fail in `collection.ivy` first though.

**Comment by prasitaGit** [comment]
> It might be worth fixing the guarantees that fail in `collection.ivy` first though.

On it.

**Comment by prasitaGit** [comment]
> It might be worth fixing the guarantees that fail in `collection.ivy` first though.

I added the if condition `if m.m_index < arr.end(my_log)` before `arr.set` to remove the errors. Is that's whats needed or do we need to add invariants?

**Comment by nano-o** [comment]
That should fix the error but it's not what we want in practice. What about resizing the array to make room for the new entry?

**Comment by prasitaGit** [comment]
> That should fix the error but it's not what we want in practice. What about resizing the array to make room for the new entry?

This will be in the else part right?

**Comment by nano-o** [comment]
I think that the problem is that you call `arr.set(m.m_index,...)` with an `m.m_index` which may be outside the array bounds. If you do that e.g. in C you might get a segmentation fault or undefined behavior at runtime. Here it violates the specification of `arr.set` and if you run it you'll probably get a runtime error too. What you should do is, before call `arr.set`, resize the array to make sure that `m.m_index` is smaller than `my_log.end`.

**Comment by prasitaGit** [comment]
> I think that the problem is that you call `arr.set(m.m_index,...)` with an `m.m_index` which may be outside the array bounds. If you do that e.g. in C you might get a segmentation fault or undefined behavior at runtime. Here it violates the specification of `arr.set` and if you run it you'll probably get a runtime error too. What you should do is, before call `arr.set`, resize the array to make sure that `m.m_index` is smaller than `my_log.end`.

I understand. But what I was wondering that do we have to keep on resizing (in a loop) until m.m_index becomes less than the size of the array?

**Comment by nano-o** [comment]
`array.resize` takes a new size, which you can set to one plus the index.

**Comment by prasitaGit** [comment]
> `array.resize` takes a new size, which you can set to one plus the index.

I did this and committed the code. To test the code with three nodes, do I have to open 3 terminals and specify a leader node in ./rsm_impl?

**Comment by nano-o** [comment]
Running `rsm_impl` without arguments should tell you what arguments it expects.

**Comment by prasitaGit** [comment]
So I ran `./rsm_impl 3 1`. I called `propose` and `query` on node 2. The output looks like this : 
```
> service_interface.propose(2,3)
> service_interface.query(2,1)
= {present:0,value:""}
> service_interface.query(2,0)
= {present:0,value:""}
```

I'm not really sure if query is returning correct.

**Comment by nano-o** [comment]
Let's start with 2 nodes. We should be able to start those two nodes in two different terminals, call propose in one of them, and see calls to `notify_decision` in both of them as a result (because a propose message was sent to the leader etc.)

With the curent `extract`  line, you're extracting a single centralized program, and not a distributed protocol that can be run on a set of nodes. Can you review https://microsoft.github.io/ivy/examples/networking.html and try to figure out how to extract a distributed protocol?

**Comment by prasitaGit** [comment]
I made the changes to support distributed implementation. I have committed them. On running for two nodes (on two terminals) : 
`./rsm_impl 2 1 1` and `./rsm_impl 2 1 2` (2 nodes and 1 is the leader). I called `service_interface.propose(8)` from node 2 (i.e., the non leader node), and then called `service_interface.query(0)` and `service_interface.query(1`) on both terminals. For both cases I get the output : `{present:0,value:""}` for both terminals. 
I don't think this is correct.

**Comment by nano-o** [comment]
Indeed there's a problem. Can you have a look at `rsm_impl.cpp` and find out what is going on? For example, are any TCP packets sent?

**Comment by prasitaGit** [comment]
I can see that  `rsm_impl::ext__net__send `is empty in `rsm_impl.cpp`. Also there is no mention of tcp other than `#include <WS2tcpip.h>`. I don't think this is expected.

**Comment by nano-o** [comment]
You should probably add net in the extract.

**Comment by prasitaGit** [comment]
If I just add `net` in the extract, then I get the error : 
`/home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/tcp.ivy: line 228: error: cannot strip parameter self from net.recv`
If I add `net(n)` in the extract, I get the error : 
`rsm_impl.ivy: line 90: error: cannot strip parameter leader from net.send`

**Comment by nano-o** [comment]
It should be `net(n)`, because we're extracting a distributed protocol. Line 90, Ivy does not see that `n = leader` (this should be true because propose messages are only sent to the leader, but Ivy does not infer this property). Without knowing that `n = leader` at line 90, projecting on `n` is illegal (in some sense, node `n` would be sending a message on behalf of another node `leader ~= n`).

**Comment by nano-o** [comment]
By `n` I mean the parameter of `service_implementation`, not the `n` variable declared at line 89. Btw it would be better to change the variable name to avoid confusion. Or as in Ken's examples, use `service_implementation(self:node)` instead of `service_implementation(n:node)`.

**Comment by prasitaGit** [comment]
I have committed the changes. I can see code in send of cpp file now. Also when I run two nodes in two terminals, I can see binding id and port displayed for both. For ex : for node 1, the first line is :  `binding id: 1 port: 5991` and similarly for node 2. 
But after propose, if i call query on index 0/1, I still get the op as : `{present:0,value:""}`

**Comment by nano-o** [comment]
I believe there is an issue with the tcp module. Can you switch to udp and try again?

**Comment by prasitaGit** [comment]
I have switched to `udp` and committed the code. I have tried with 2 nodes (1 and 2, 1 being the leader). I called `propose(8) `from 2. On `query(0)` I can see the result is reflected in node 1 but not node 2. The op at node 1 is : `{present:0,value:"8"}` and 2 is : `{present:0,value:""}`

**Comment by nano-o** [comment]
One issue might be that nodes are numbered starting from 0. So with a size of 2, the node datatype contains node 0 and 1, but not node 2.

**Comment by nano-o** [comment]
So the iterator in the send loop will stop at 1.

**Comment by nano-o** [comment]
If you get it to work, can you then go back to using tcp and try to diagnose the problem? It has to do with packets being dropped while TCP connections are not established. Alternatively you could treat TCP connections as a lossy channels and introduce ack messages with re-transmission after a timeout if you don't get an acknowledgment.

**Comment by prasitaGit** [comment]
It is working. How do I treat TCP connections as lossy channels? Do I introduce the timeout module?

**Comment by prasitaGit** [comment]
Also why do we have to do it in TCP?

**Comment by nano-o** [comment]
Well, you could also keep using udp and add the ack/retransmission mechanism over udp, as udp is definitely lossy (there's no guarantee that a packet will be delivered). In any case, we'll need an ack/retransmission mechanism for a realistic protocol.

**Comment by nano-o** [comment]
UDP might have other problems though. For example, sending packets larger than the MTU causes problems if I remember.

**Comment by prasitaGit** [comment]
> If you get it to work, can you then go back to using tcp and try to diagnose the problem? It has to do with packets being dropped while TCP connections are not established. Alternatively you could treat TCP connections as a lossy channels and introduce ack messages with re-transmission after a timeout if you don't get an acknowledgment.

Is there any suitable standard example of this that I can lookup and model my code?

**Comment by nano-o** [comment]
https://microsoft.github.io/ivy/examples/sht/trans.html

**Comment by prasitaGit** [comment]
My github was down for a couple of days. So i have been trying to implement the reliable communication. Initially I was trying to incorporate the trans and queue, but we don't need all the features as you said. Right now i am just concentrating on the receipt of ack messages after time out. For this I am maintaining another log/array to record messages that have been proposed (i.e., in the propose action) and after timeout i am going to check whether all the messages in the array have been recorded in `my_log` or not. Is this the right direction to go?

**Comment by nano-o** [comment]
Yes that sounds good.

**Comment by prasitaGit** [comment]
I have done some changes and committed them. Right now I have tested with two nodes. I can see that the leader is able to update the value and not the other node. But when the leader itself sends the message, on querying it I don't get the result. The execution scenario is depicted below : 

Node 1 (Other node) : 
```
> binding id: 1 port: 5991
service_interface.propose(5)
> < service_interface.notify_decision(1,"5")
service_interface.query(0) (nothing is shown);
```

Node 0 (Leader) : 
 ```
binding id: 0 port: 5990
< service_interface.notify_decision(1,"5")
> service_interface.query(0)
= {present:0,value:"5"}
> service_interface.propose(8)
> < service_interface.notify_decision(2,"8")
> service_interface.query(0)
= {present:0,value:"5"}
> service_interface.query(1)
= {present:0,value:"5"}
```

**Comment by nano-o** [comment]
The first problem I see is that `notify_decision` says that `5` was decided at position `1`, and not `0`.

**Comment by prasitaGit** [comment]
I can see on `ivy_show` that `arr.empty()` is empty. It looks like this : 

```
action ext:arr.empty returns(a:arr) = {
    <<<
    >>>
}
```
At first I thought I am setting the index one more than the actual, but after repeated debugging and on `ivy_show` display I feel that I am not including appropriate files/something else needs to be added to the isolate. I am unable to understand what is missing.

**Comment by nano-o** [comment]
Have a look at `collections.ivy` and check what the implementation should be. It could be empty because it uses C++ vectors, which by default are initialized as empty when they are declared. Also check `rsm_impl.cpp` to see what code is generated (e.g. `rsm_impl::__init()`); you can debug the program as a regular C++ binary with gdb or by manually editing the sources and adding debug print statements.

**Comment by prasitaGit** [comment]
I can see that for `rsm_impl::_init() `appropriate code is generated : 

`service_implementation__my_log = ext__arr__empty();` I checked `collections.ivy`, and I think i am declaring it correctly. But I am not sure what isolate to specify with ivy_show to get a detailed check.

**Comment by nano-o** [comment]
What about the method `ext__arr__empty()`? Is it doing the right thing?
Isolate `impl` would be the isolate to show to investigate code generation setup (it's the isolate that contains all the code to generate when running `ivyc isolate=impl ...`

**Comment by nano-o** [comment]
Another debugging trick that you can use is to declare an imported action, e.g. `import action my_debug_action(i:inst_t)`, without any implementation. Ivy will give it a default implementation which just prints the name of the action and its parameters on the console. So you can call it from another action in order to display debug information.

**Comment by prasitaGit** [comment]
> What about the method `ext__arr__empty()`? Is it doing the right thing?
> Isolate `impl` would be the isolate to show to investigate code generation setup (it's the isolate that contains all the code to generate when running `ivyc isolate=impl ...`

`ext_arr_empty()` does not contain anything in its body. I noticed this yesterday but didn't realize that it could be the problem. Here is the body of this function : 

```
rsm_impl::arr rsm_impl::ext__arr__empty(){
    rsm_impl::arr a;
    {

    }
    return a;
}

```

**Comment by nano-o** [comment]
This looks fine: it declares the return value `a` of type `rsm_impl::arr` (which as you can see in `rsm_impl.h` is a C++ `vector`) which in C++ means that the default constructor is called, which makes `a` the empty vector. Then `a` is returned.

**Comment by prasitaGit** [comment]
I have committed the changes. Debugging with import action helped. It works fine with 2 nodes now. Here is the tested log : 

Node 0 (leader) : 

```
> binding id: 0 port: 5990
< service_implementation.my_debug_action(0)
< service_implementation.my_debug_action(0)
< service_implementation.my_debug_action(1)
< service_implementation.my_debug_action(2)
service_interface.query(0)
= {present:0,value:"8"}
> service_interface.query(1)   
= {present:0,value:"7"}
> service_interface.query(2)
= {present:0,value:"6"}
> service_interface.query(3)
= {present:0,value:""}
> service_interface.propose(5)
> < service_implementation.my_debug_action(3)
service_interface.query(3)
= {present:0,value:"5"}
```

Node 1 : 

```
> binding id: 1 port: 5991
service_interface.propose(8)
> < service_interface.notify_decision(0,"8")
service_interface.propose(7)
> < service_interface.notify_decision(1,"7")
service_interface.propose(6)
> < service_interface.notify_decision(2,"6")
service_interface.query(0)
= {present:0,value:"8"}
> service_interface.query(1)
= {present:0,value:"7"}
> service_interface.query(2)
= {present:0,value:"6"}
> service_interface.query(3)
= {present:0,value:""}
> < service_interface.notify_decision(3,"5")
service_interface.query(4)
= {present:0,value:""}
> service_interface.query(3)
= {present:0,value:"5"}
```

**Comment by nano-o** [comment]
Okay, that's good! There are a couple issues though.

One minor issue is that `present` should be set to true to indicate that the log contains something at the queried position.

I see that you chose to not add anything that's already somewhere in the log. That's okay for now but we might revisit that decision in the future. I understand that allowing duplicates in the log makes it harder to implement retransmission, but we could solve that at the transport level by giving sequence numbers to messages. 

A more important issue is that if node `0` proposes `a` and concurrently node 1 proposes `b`, then at least one of them will re-transmit its proposal forever: let's say node `0` reaches the leader first; then node one will have `b` at position 0 in `proposed_log` and `a` at position 0 in `my_log` and `check` will be false. Retransmission should only happen if the proposal is nowhere to be found in the log.

**Comment by prasitaGit** [comment]
> Okay, that's good! There are a couple issues though.
> 
> One minor issue is that `present` should be set to true to indicate that the log contains something at the queried position.
> 
> I see that you chose to not add anything that's already somewhere in the log. That's okay for now but we might revisit that decision in the future. I understand that allowing duplicates in the log makes it harder to implement retransmission, but we could solve that at the transport level by giving sequence numbers to messages.
> 
> A more important issue is that if node `0` proposes `a` and concurrently node 1 proposes `b`, then at least one of them will re-transmit its proposal forever: let's say node `0` reaches the leader first; then node one will have `b` at position 0 in `proposed_log` and `a` at position 0 in `my_log` and `check` will be false. Retransmission should only happen if the proposal is nowhere to be found in the log.

I have fixed the `present` value. For the issue you say at last, if you look at my inner loop in action `timer.timeout`, it iterates through the entire `my_log` and if the proposed value is not found anywhere in `my_log`, then check remains false and we re transmit. I tried replicating concurrent transmission from 2 different nodes. I didn't get an infinite loop but I saw the same value getting inserted at two different indices. I can't figure out this reason. Here is the flow : 

Node 0 (leader) : 

```
> binding id: 0 port: 5990
service_interface.propose(8)
> < service_implementation.my_debug_action(0)
< service_implementation.my_debug_action(1)
service_interface.query(0)
= {present:1,value:"8"}
> service_interface.query(1)
= {present:1,value:"7"}
> service_interface.query(2)    
= {present:0,value:""}
```


Node 1 (other node) : 

```
> binding id: 1 port: 5991
service_interface.propose(7)
> < service_interface.notify_decision(1,"7")
service_interface.query(0)
= {present:1,value:"7"}
> service_interface.query(1) 
= {present:1,value:"7"}
> service_interface.query(2)
= {present:0,value:""}

```

**Comment by nano-o** [comment]
Hi Prasita, any luck fixing this?

**Comment by prasitaGit** [comment]
Not yet. But I am always getting this and not infinite loop violation (as you mentioned as the major issue)

**Comment by nano-o** [comment]
Can you try debugging it as a C++ application first (I mean you debug and edit the C++ code directly instead of re-generating it)?

**Comment by prasitaGit** [comment]
I will. But before that, I would like to explain the exact situation going on here. This is happening just for the first time. The leader node (node 0) sends 8 and the other node sends 7. They are concurrent, but 8 is sent first (i.e., I clicked on sending of 8 first). In this case I see that, even though 8 is sent to node 1, node 1 never receives it. Here is the status : 

Node 0 (leader). : 

```
service_interface.propose(8)   
> < service_implementation.my_debug_action(0)
< service_implementation.my_debug_node(1)
< service_implementation.my_debug_value("8")
< service_implementation.my_debug_action(1)
< service_implementation.my_debug_node(1)
< service_implementation.my_debug_value("7")
service_interface.query(0)  
= {present:1,value:"8"}
> service_interface.query(1)  
= {present:1,value:"7"}
```

Node 1 (other node) : 

```
service_interface.propose(7)
> < service_implementation.my_debug_value("7")
< service_implementation.my_debug_value("7")
< service_interface.notify_decision(1,"7")
```

The infinite loop scenario that you mentioned happens when I send the proposal of the other node (i.e., 7) first. But I fail to understand the reason, as I have a nested loop in `timer.timeout`, where retransmission happens only if the proposed value is found nowhere in `my_log`

**Comment by nano-o** [comment]
>I will. But before that, I would like to explain the exact situation going on here. This is happening just for the first time. The leader node (node 0) sends 8 and the other node sends 7. They are concurrent, but 8 is sent first (i.e., I clicked on sending of 8 first). In this case I see that, even though 8 is sent to node 1, node 1 never receives it.

It looks like "8" is inserted into the log of node 0, and thus, even though the message to node 1 is lost, node 0 never re-transmits it to node 1.

**Comment by prasitaGit** [comment]
> > I will. But before that, I would like to explain the exact situation going on here. This is happening just for the first time. The leader node (node 0) sends 8 and the other node sends 7. They are concurrent, but 8 is sent first (i.e., I clicked on sending of 8 first). In this case I see that, even though 8 is sent to node 1, node 1 never receives it.
> 
> It looks like "8" is inserted into the log of node 0, and thus, even though the message to node 1 is lost, node 0 never re-transmits it to node 1.

To remove the above error (as well as the infinite loop condition), I would have to check the contents of `my_log` for every node with respect to the `proposed_log` for self. I'm failing to implement this within `service_implementation`, as it takes as input the parameter self.

**Comment by nano-o** [comment]
Yes, you can't do that because it's a distributed system. The only thing you can do to other nodes is send them messages.

Here we must make sure that the decisions that the leader makes are acknowledged by all. A possible solution is for the leader to track, for each position in the log, what are the nodes that acknowledged its decision message (of this implies that nodes send an "ack" message in response to the leader's decision message).

Conversely a node that makes a proposal and never receives a decision for it from the leader should re-send it. To to this a node can track all its outsanding proposals (e.g. in a set) and periodically resend them to the leader.

**Comment by prasitaGit** [comment]
I have committed the changes. I have an `ack_msg` and the struct that we talked about implemented. I have modified the `timeout` function accordingly. I can see that the `ack_msg` never gets delivered. The case that always happens is if the leader proposes a value, it does not reach the first time. It times out and proposes again, this time it reaches the other node but the ack does not reach and it keeps looping like this forever. The trace is given below : 

Node 0 (leader) : 

```
service_interface.propose(8)
> < service_implementation.my_debug_node(0)
< service_implementation.my_debug_node(0)
< service_implementation.my_debug_node(0)
< service_implementation.my_debug_node(0)
< service_implementation.my_debug_node(0)
< service_implementation.my_debug_node(0)
< service_implementation.my_debug_node(0)
```

Node 1 : 

```
< service_implementation.my_debug_value("8")
< service_interface.notify_decision(0,"8")
< service_interface.notify_decision(0,"8")
< service_interface.notify_decision(0,"8")
< service_interface.notify_decision(0,"8")
< service_interface.notify_decision(0,"8")
< service_interface.notify_decision(0,"8")
< service_interface.notify_decision(0,"8")
```

**Comment by prasitaGit** [comment]
I have committed the changes. I am not getting concurrency violations for 2 nodes anymore. I have the ack_msg and struct that we talked about. Could you check and let me know. I haven't added sequence numbers yet.

**Comment by nano-o** [comment]
Just to clarify (I haven't had time to look at the code yet), what is not working so far that would require sequence numbers?

**Comment by prasitaGit** [comment]
If we incorporate duplicate values then it would require sequence number as well as node id.

**Comment by nano-o** [comment]
Okay, then it would already be a good exercise to prove that the current code implements the RSM specification. Would you like to try that?

**Comment by prasitaGit** [comment]
You mean fixing all the invariants?

**Comment by nano-o** [comment]
Yes, including the pre and post conditions of the interface.

**Comment by prasitaGit** [comment]
I had 8 failed checks. I introduced an invariant : `invariant ~service_interface.log(self,I,V) -> ~(arr.value(my_log,I) = V)`. I have 2 failed checks now. But this invariant fails on initialization. I think log is true on initialization, whereas i initialize it to false. On running `ivyc isolate=impl rsm_impl.ivy `i don't see the initialization of propose and log. Here is the trace : 

```
searching for a small model... done
[
    ack_msg_type.node_reply(0) = 0
    @I = 0
    value_opt_t.present(0) = false
    msg.m_kind(0) = msg_kind.decision_msg
    @V0 = 0
    node.succ(0,0) = false
    node.iter.is_end(0) = false
    arr_ack.end(0) = 0
    0:inst_t = 0
    @V = ""
    0:node < 0 = false
    arr_ackmsg.end(0) = 0
    0:node = 0
    0:inst_t < 0 = false
    msg.m_index(0) = 0
    inst_t.succ(0,0) = false
    node.max = 0
    msg.m_node(0) = 0
    node.iter.val(0) = 0
    arr.end(0) = 0
]
init

{
    /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/tcp.ivy: line 180: net.sent(V,N) := false

    [
        net.sent(0,0) = false
    ]
    rsm_impl.ivy: line 59: service_interface.proposed(Yprm:V0,V) := false

    rsm_impl.ivy: line 60: service_interface.log(Yprm:V0,I,V) := false

    [
        fml:a = 0
    ]
    rsm_impl.ivy: line 89: call service_implementation.my_log(Yprm:V0) := arr.empty
    {
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 89: assume arr.end(fml:a) = 0

    }

    [
        service_implementation.my_log(0) = 0
    ]
    rsm_impl.ivy: line 90: call service_implementation.proposed_log(Yprm:V0) := arr.empty
    {
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 89: assume arr.end(fml:a) = 0

    }

    [
        fml:a = 0
        service_implementation.proposed_log(0) = 0
    ]
    rsm_impl.ivy: line 91: call service_implementation.ack_log(Yprm:V0) := arr_ackmsg.empty
    {
        [
            fml:a = 0
            fml:a = 0
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 89: assume arr_ackmsg.end(fml:a) = 0

        [
            fml:a = 0
            fml:a = 0
        ]
    }

    [
        service_implementation.ack_log(0) = 0
        fml:a = 0
        fml:a = 0
    ]
}

```

**Comment by nano-o** [comment]
The array bounds should appear somewhere in the invariant. As far as I remember, the specification of array does not say anything about the value relation beyond the end of the array.

**Comment by prasitaGit** [comment]
I have committed some changes. I removed one invariant and changed the bi implication to implication sign of the uncommented invariant. But now when I run ivy_check rsm_impl.ivy, it hangs in step :` rsm_impl.ivy: line 274: service_implementation.invar262(V0:node) ...`

**Comment by nano-o** [comment]
There is no problem line 274 on my side (although there are other errors). Please check that you pulled the last version of Ivy from github.

**Comment by prasitaGit** [comment]
I have been trying multiple combinations and they are failing. Ultimately I removed all the invariants and just tried with one : 
`invariant service_interface.proposed(self,V) -> ((arr.value(proposed_log,I) = V) & (I < arr.end(proposed_log)))`. This resolves some of the pre-condition , post-condition but gives the violation in `propose`. I have been trying to understand but don't get it. Here is the trace : 

```
searching for a small model... done
[
    ack_msg_type.node_reply(0) = 0
    @I = 1
    value_opt_t.present(0) = false
    msg.m_kind(0) = msg_kind.propose_msg
    @V0 = 0
    node.succ(0,0) = false
    arr_ackmsg.value(0,1) = 0
    arr_ackmsg.value(0,0) = 0
    arr_ackmsg.value(1,1) = 0
    arr_ackmsg.value(1,0) = 0
    node.iter.is_end(0) = false
    arr.end(0) = 0
    arr.end(1) = 1
    0:node < 0 = false
    node.max = 0
    0:inst_t = 0
    arr_ackmsg.end(0) = 1
    arr_ackmsg.end(1) = 0
    0:node = 0
    0:inst_t < 1 = true
    1:inst_t < 1 = false
    1:inst_t < 0 = false
    0:inst_t < 0 = false
    msg.m_index(0) = 1
    inst_t.succ(1,1) = false
    inst_t.succ(1,0) = false
    inst_t.succ(0,1) = false
    inst_t.succ(0,0) = false
    @V = ""
    msg.m_node(0) = 0
    leader = 0
    node.iter.val(0) = 0
    arr_ack.end(0) = 0
    net.sent(0,0) = false
    service_implementation.proposed_log(0) = 0
    service_implementation.ack_log(0) = 1
]
call service_interface.propose

{
    [
        fml:v = ""
        prm:V0 = 0
    ]
    rsm_impl.ivy: line 57: assume (service_interface.log(V0,I,V1) & service_interface.log(V0,I,V2)) -> V1 = V2

    rsm_impl.ivy: line 68: service_interface.proposed(prm:V0,fml:v) := true

    [
        loc:m = 0
    ]
    rsm_impl.ivy: line 95: msg.m_kind(loc:m) := msg_kind.propose_msg

    rsm_impl.ivy: line 96: msg.m_value(loc:m) := fml:v

    rsm_impl.ivy: line 97: call service_implementation.proposed_log(prm:V0) := arr.append(service_implementation.proposed_log(prm:V0), fml:v)
    {
        [
            fml:v_a = ""
            old_fml:a_a = 0
            fml:a_a = 0
        ]
        fml:a := *

        [
            fml:a_a = 1
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 119: assume (arr.end(fml:a) > arr.end(old_fml:a) & ~(arr.end(old_fml:a) < X & X < arr.end(fml:a)))

        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 121: assume (0:inst_t <= X & X < arr.end(old_fml:a)) -> arr.value(fml:a,X) = arr.value(old_fml:a,X)

        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 122: assume arr.value(fml:a,arr.end(old_fml:a)) = fml:v

    }

    [
        loc:mack = 0
        service_implementation.proposed_log(0) = 1
    ]
    rsm_impl.ivy: line 101: ack_msg_type.val(loc:mack) := fml:v

    [
        fml:a = 0
    ]
    rsm_impl.ivy: line 102: call ack_msg_type.node_reply(loc:mack) := arr_ack.empty
    {
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 89: assume arr_ack.end(fml:a) = 0

    }

    rsm_impl.ivy: line 103: call service_implementation.ack_log(prm:V0) := arr_ackmsg.append(service_implementation.ack_log(prm:V0), loc:mack)
    {
        [
            fml:a_a = 1
            fml:v = 0
            old_fml:a_a = 1
        ]
        fml:a := *

        [
            fml:v = ""
            old_fml:a_a = 0
            fml:a_a = 0
            fml:v = 0
            old_fml:a_a = 1
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 119: assume (arr_ackmsg.end(fml:a) > arr_ackmsg.end(old_fml:a) & ~(arr_ackmsg.end(old_fml:a) < X & X < arr_ackmsg.end(fml:a)))

        [
            fml:v = ""
            old_fml:a_a = 0
            fml:v = 0
            old_fml:a_a = 1
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 121: assume (0:inst_t <= X & X < arr_ackmsg.end(old_fml:a)) -> arr_ackmsg.value(fml:a,X) = arr_ackmsg.value(old_fml:a,X)

        [
            fml:v = ""
            old_fml:a_a = 0
            fml:v = 0
            old_fml:a_a = 1
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/collections.ivy: line 122: assume arr_ackmsg.value(fml:a,arr_ackmsg.end(old_fml:a)) = fml:v

        [
            fml:v = ""
            old_fml:a_a = 0
            fml:v = 0
            old_fml:a_a = 1
        ]
    }

    [
        fml:v = ""
        old_fml:a_a = 0
        service_implementation.ack_log(0) = 0
        old_fml:a_a = 1
    ]
    rsm_impl.ivy: line 106: call net.send(prm:V0, leader, loc:m)
    {
        [
            fml:v = 0
            fml:dst = 0
            old_fml:a_a = 0
            fml:src = 0
            old_fml:a_a = 1
        ]
        /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/tcp.ivy: line 184: net.sent(fml:v,fml:dst) := true

        [
            fml:v = ""
            fml:v = 0
            old_fml:a_a = 0
            net.sent(0,0) = true
            old_fml:a_a = 1
        ]
    }

    [
        fml:v = ""
        old_fml:a_a = 0
        old_fml:a_a = 1
    ]
}

```
I have a total of 6 failed checks.

**Comment by nano-o** [comment]
Shouldn't the invariant be:
`invariant service_interface.proposed(self,V) -> exists I . ((arr.value(proposed_log,I) = V) & (I < arr.end(proposed_log)))`?
Not that you can use `complete=fo` on the command line if the fragment checker gets in your way.

It also seems that the isolate should be
`isolate service_implementation_iso = service_implementation with service_interface, inst_t, arr, arr_ack, arr_ackmsg, net, node, net`.

**Comment by prasitaGit** [comment]
> Shouldn't the invariant be:
> `invariant service_interface.proposed(self,V) -> exists I . ((arr.value(proposed_log,I) = V) & (I < arr.end(proposed_log)))`?
> Not that you can use `complete=fo` on the command line if the fragment checker gets in your way.
> 
> It also seems that the isolate should be
> `isolate service_implementation_iso = service_implementation with service_interface, inst_t, arr, arr_ack, arr_ackmsg, net, node, net`.

Could you elaborate this fragment checker error? I got it and using `complete=fo` I resolved it, but I didn't get the reason behind fragment checker error.

**Comment by nano-o** [comment]
Ivy says:
```
The following terms may generate an infinite sequence of instantiations:
rsm_impl.ivy: line 273: arr.value(service_implementation.proposed_log(V0_p),I) = V_b
```
I'm not sure why it's not showing `exists I . proposed_log.value(I) = V`.
This is outside FAU because `arr.value` maps `inst_t` to `value_t` and the existential quantifier on `I`, being under the scope of universal quantification on `V`, creates a reverse dependency from `value_t` to `inst_t`, which forms a cycle.

**Comment by nano-o** [comment]
One way to avoid this cycle is to use `rel_array` instead of array. `rel_array` uses a `value` relation instead of a function.

**Comment by prasitaGit** [comment]
I have added further invariants. Right now I have three failed checks. One invariant : `invariant net.sent(M,self) <->  service_interface.log(self,I,V)` is failing on `timer.timeout` because `net.sent` is true after `timer.timeout` in the trace, but I can't see how is `net.send` getting executed as all the arrays are empty : 

```
searching for a small model... done
[
    ack_msg_type.node_reply(0) = 0
    @I = 0
    arr.value(0,0) = 0
    value_opt_t.present(0) = false
    msg.m_kind(0) = msg_kind.ack_msg
    value_opt_t.value(0) = 0
    @V0 = 0
    node.succ(0,0) = false
    node.iter.is_end(0) = false
    arr_ack.end(0) = 0
    net.received(0,0) = false
    ack_msg_type.val(0) = 0
    service_interface.log(0,0,0) = false
    0:inst_t = 0
    @V = 0
    0:node < 0 = false
    @M = 0
    arr_ackmsg.end(0) = 0
    msg.m_value(0) = 0
    0:node = 0
    0:inst_t < 0 = false
    msg.m_index(0) = 0
    inst_t.succ(0,0) = false
    node.max = 0
    msg.m_node(0) = 0
    node.iter.val(0) = 0
    arr.end(0) = 0
    net.sent(0,0) = false
]
call service_implementation.timer.timeout

{
    [
        prm:V0 = 0
    ]
    rsm_impl.ivy: line 211: loc:idp := 0:inst_t

    [
        loc:idp = 0
    ]
    rsm_impl.ivy: line 212: net.sent := *

    rsm_impl.ivy: line 212: loc:idp := *

    rsm_impl.ivy: line 232: loc:idp := 0:inst_t

    rsm_impl.ivy: line 233: net.sent := *

    [
        net.sent(0,0) = true
    ]
    rsm_impl.ivy: line 233: loc:idp := *

}
```

**Comment by nano-o** [comment]
This invariant is strange: `invariant net.sent(M,self) <-> service_interface.log(self,I,V)`
There's no relation between the message `M`, the index `I`, and the value `V`.

Similarly for this one: `service_interface.proposed(self,V) -> net.sent(M,self)`.
Maybe you meant something like `service_interface.proposed(self,V) -> exists M:msg . net.sent(M,leader) & M.m_value = V & M.m_type = msg_kind.propose_msg & M.m_node = self` ?

**Comment by prasitaGit** [comment]
> This invariant is strange: `invariant net.sent(M,self) <-> service_interface.log(self,I,V)`
> There's no relation between the message `M`, the index `I`, and the value `V`.
> 
> Similarly for this one: `service_interface.proposed(self,V) -> net.sent(M,self)`.
> Maybe you meant something like `service_interface.proposed(self,V) -> exists M:msg . net.sent(M,leader) & M.m_value = V & M.m_type = msg_kind.propose_msg & M.m_node = self` ?

Yes. Actually I wasn't able to do `M.m_node` because i didn't put `exists M:msg`, hence I was getting the error that M could not be identified. I will try this now.

**Comment by nano-o** [comment]
If you don't explicitly give a type to `M`, then you can use `msg.m_node(M)`.

**Comment by prasitaGit** [comment]
`invariant service_interface.proposed(self,V) -> exists M:msg . net.sent(M,leader) & M.m_value = V & M.m_type = msg_kind.propose_msg & M.m_node = self`
Is this giving an infinite wait at your end? I did update ivy.

**Comment by nano-o** [comment]
Yes it does hang (after substituting `m_kind` for `m_type`). The verification conditions are not in a decidable fragment here, which means that Z3 will diverge unpredictably. In this case it becomes really difficult to debug things, and a better route often is to try to keep verification conditions decidable.

It's can be difficult to keep VCs decidable without resorting to some kind of refinement, but maybe here you can do it. You can find an example of refinement in `paxos.ivy`.

**Comment by prasitaGit** [comment]
Could you give me the link to the file? I can't seem to find the file in ivy/doc/examples

**Comment by nano-o** [comment]
It's in this repository here (ivy-proofs/paxos)

**Comment by prasitaGit** [comment]
I looked into it. I did not understand what is exactly meant by refinement and where in paxos.ivy is it encoded? it'd be great to have some clarity.

**Comment by nano-o** [comment]
In `paxos.ivy` the `protocol` isolate is a refinement of the `abs` isolate. In the `abs` isolate, we do not model `one_b` messages, and because of this we avoid quantification on the components of `one_b` messages. We model `one_b` messages in the `protocol` isolate, where we only give invariants that establish a relation between the state of `abs` and the state of `protocol`. Once this relation is established, the agreement property of `abs` implies the agreement property of `protocol`.

One thing you could do is try to prove the agreement property of `protocol` without using `abs` at all. Then you'll see what kind of quantifiers you get and how using `abs` eliminates them.

This is the same idea as in the leader election-example of the ivy tutorial, where a concrete spec that includes the network refines a more abstract spec.
 
Does this make things clearer?

**Comment by prasitaGit** [comment]
I had to reset my computer for some reasons and wasn't able to work for a while. I have installed ubuntu20 and python3 with pip (python3-pip). Doesn't ivy work with pip at all?

**Comment by nano-o** [comment]
It only works with python 2.

**Comment by prasitaGit** [comment]
I am trying to install ivy with python 2 from here : `http://microsoft.github.io/ivy/install.html`. However, when I come to the step : `sudo python setup.py install `I'm stuck with this error : 
```
  File "/tmp/easy_install-LK4K25/pyparsing-3.0.0a2/pyparsing/core.py", line 168
    nonlocal found_arity, limit
                       ^
SyntaxError: invalid syntax
```

I searched about this error, and I got response that nonlocal is configured with python3 and to resolve it in python 2, I need to set this : `pip install pyparsing==1.5.7 `(pyparsing version to 1.5.7) but this did not work either. I did not face these problems before.

**Comment by nano-o** [comment]
Are you using a virtualenv? This is an easy way to create a clean python2 environment where there's no confusion between python2 and python3

**Comment by prasitaGit** [comment]
I'm not. Do you mind sharing the virtualenv commands again?
